logging:
  level:
    org.springframework.security: trace
    org.example.springboot3oauth2security: trace

spring:
  application:
    name: spring-boot-3-oauth2-security
  messages:
    basename: i18n/messages
    encoding: UTF-8
    use-code-as-default-message: true
  thymeleaf:
    suffix: .html # this is default setting